// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/concierges": {
            "get": {
                "description": "Returns the names and static settings of every loaded Concierge, sorted alphabetically.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "concierges"
                ],
                "summary": "List registered concierges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_server.conciergeItem"
                            }
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "description": "Returns every session ordered by updated_at descending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "List all sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new Session from the named Concierge's current settings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create a session",
                "parameters": [
                    {
                        "description": "Concierge to instantiate",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.createSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "delete": {
                "tags": [
                    "sessions"
                ],
                "summary": "Delete a session and its conversation data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Update a session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Session changes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.updateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/history": {
            "get": {
                "description": "Returns the session row plus every message in its (unpruned) tree, so the client can reconstruct and switch between branches itself.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get full session history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.historyResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages": {
            "post": {
                "description": "Sends a user message (or slash command) into a session and returns the assistant's reply.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Send a message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message to send",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages/stream": {
            "post": {
                "description": "Like sendMessage, but streams typed assistant progress as Server-Sent Events (\"delta\", \"reasoning\", \"tool_call\", \"tool_output\", \"tool_result\", and \"session_updated\" events), finishing with a \"done\" event carrying the same body sendMessage would return (or an \"error\" event).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Send a message with streaming",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message to send",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages/{messageID}/continue/stream": {
            "post": {
                "description": "Resumes generation at messageID, an incomplete assistant message on the session's active path, using its persisted content as the model's prefix. Streams only the newly generated suffix as Server-Sent Events, finishing with a \"done\" event carrying the same body sendMessage would return (or an \"error\" event).",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Resume an incomplete assistant reply with streaming",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Incomplete assistant message ID",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages/{messageID}/edit": {
            "post": {
                "description": "Creates an edited sibling of an assistant message without invoking the LLM, then makes the new message the session's active leaf.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Edit an assistant message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Assistant message ID",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edited assistant content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.editAssistantMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/regenerate": {
            "post": {
                "description": "Re-answers the nearest ancestor user message on the session's active path, creating a sibling assistant branch rather than a new user message.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Regenerate the last reply",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/regenerate/stream": {
            "post": {
                "description": "Like regenerate, but streams typed assistant progress as Server-Sent Events, finishing with a \"done\" event.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Regenerate the last reply with streaming",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_store_SessionSettings": {
            "type": "object"
        },
        "github_com_Cyvadra_hephaestus_internal_store.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parentMessageID": {
                    "description": "ParentMessageID is nil for the first message of a session.",
                    "type": "integer"
                },
                "reasoningContent": {
                    "description": "ReasoningContent holds chain-of-thought output, when the model\nprovided one.",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sessionID": {
                    "type": "integer"
                },
                "status": {
                    "description": "Status is complete unless generation ended before the Agent finished.",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "toolCallID": {
                    "description": "ToolCallID links a tool-role message back to the assistant\nmessage's tool_calls entry it answers.",
                    "type": "string"
                },
                "toolCalls": {
                    "description": "ToolCalls is the raw tool_calls payload for an assistant message,\nor empty for other roles.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.Project": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.Session": {
            "type": "object",
            "properties": {
                "activeLeafMessageID": {
                    "description": "ActiveLeafMessageID points at the tip of the currently active\nbranch in ChatMessage; nil for a session with no messages yet.",
                    "type": "integer"
                },
                "compressionID": {
                    "description": "CompressionID references the most recently applicable Compression\nrow for this session, if any.",
                    "type": "integer"
                },
                "compressionLastMessageID": {
                    "description": "CompressionLastMessageID is the ChatMessage id up to which\nCompressionID's compression covers.",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "flagArchived": {
                    "type": "boolean"
                },
                "flagPinned": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "project": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Project"
                },
                "projectID": {
                    "type": "integer"
                },
                "settings": {
                    "description": "Settings is the live, mutable configuration for this session.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_store_SessionSettings"
                        }
                    ]
                },
                "sourceConcierge": {
                    "description": "SourceConcierge is the Concierge name used at creation time, kept\nfor reference only; it has no further business influence.",
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "description": "Title and Summary are maintained by the session-summary Plugin\n(title \u003c=20 chars, summary \u003c=300 chars per design doc); both are\nempty until that plugin has run at least once.",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_server.conciergeItem": {
            "type": "object",
            "properties": {
                "identity": {
                    "type": "string"
                },
                "impressions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "plugins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tool_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_server.createSessionRequest": {
            "type": "object",
            "required": [
                "concierge"
            ],
            "properties": {
                "concierge": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                }
            }
        },
        "internal_server.editAssistantMessageRequest": {
            "type": "object",
            "required": [
                "active_leaf_message_id",
                "content"
            ],
            "properties": {
                "active_leaf_message_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "reasoning_content": {
                    "type": "string"
                }
            }
        },
        "internal_server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_server.historyResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.ChatMessage"
                    }
                },
                "session": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                }
            }
        },
        "internal_server.sendMessageRequest": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "active_leaf_message_id": {
                    "description": "ActiveLeafMessageID, when set, switches the session onto this\nbranch before the message is processed (see design doc's session\nbranching semantics). Required for every continuation, per doc.",
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_server.sendMessageResponse": {
            "type": "object",
            "properties": {
                "command_response": {
                    "description": "CommandResponse is set (and never persisted) when Text was a slash command.",
                    "type": "string"
                },
                "message": {
                    "description": "Message is the persisted final assistant ChatMessage for a chat turn.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.ChatMessage"
                        }
                    ]
                },
                "metadata": {
                    "description": "Metadata carries any plugin-attached data for this turn (e.g.\nsuggested next-user-message alternatives).",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "internal_server.updateSessionRequest": {
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "pinned": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hephaestus API",
	Description:      "Single-user AI agent framework: sessions, chat turns, slash commands.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
