// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/concierges": {
            "get": {
                "description": "Returns the names and static settings of every loaded Concierge, sorted alphabetically.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "concierges"
                ],
                "summary": "List registered concierges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_server.conciergeItem"
                            }
                        }
                    }
                }
            }
        },
        "/configurations/catalog": {
            "get": {
                "description": "Returns names from the active database registry and registered tools/plugins.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configurations"
                ],
                "summary": "List available configuration references",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_registry.Catalog"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/configurations/{kind}": {
            "get": {
                "description": "Returns all database-backed configuration records. The kind must be identities, impressions, tool-groups, concierges, workflows, jobs, or constants.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configurations"
                ],
                "summary": "List configurations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Persists a configuration. The change becomes active for new requests and subsequent chat turns immediately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configurations"
                ],
                "summary": "Create a persisted configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration payload determined by kind",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/configurations/{kind}/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configurations"
                ],
                "summary": "Get a persisted configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Configuration name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Replaces a configuration. The path and payload names must match, and the change becomes active for new requests and subsequent chat turns immediately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configurations"
                ],
                "summary": "Replace a persisted configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Configuration name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration payload determined by kind",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a configuration immediately. A same-named default template is restored only after the next process start.",
                "tags": [
                    "configurations"
                ],
                "summary": "Delete a persisted configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configuration kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Configuration name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/job-runs": {
            "get": {
                "description": "Lists job runs, newest first, with optional job-name filter and bounded pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List job runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by job name",
                        "name": "job",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Result offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.JobRun"
                            }
                        }
                    }
                }
            }
        },
        "/job-runs/{id}": {
            "get": {
                "description": "Returns a job run with its attempted workflow runs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get a job run",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.jobRunDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/job-runs/{id}/cancel": {
            "post": {
                "description": "Requests cancellation of an active job run.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Cancel a job run",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{name}": {
            "delete": {
                "description": "Deletes a non-default project only when it has no sessions. Its project directory is deleted only when requested.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Delete an empty project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Deletion options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_server.deleteProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "description": "Returns every session ordered by last_message_time descending.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "List all sessions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new Session from the named Concierge's current settings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create a session",
                "parameters": [
                    {
                        "description": "Concierge to instantiate",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.createSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}": {
            "delete": {
                "tags": [
                    "sessions"
                ],
                "summary": "Delete a session and its conversation data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Update a session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Session changes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.updateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/attachments/{attachmentID}/download": {
            "get": {
                "description": "Downloads a file explicitly delivered by an assistant message. The referenced Project file is revalidated at download time.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Download an assistant attachment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Attachment ID",
                        "name": "attachmentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/history": {
            "get": {
                "description": "Returns the session row plus every message in its (unpruned) tree, so the client can reconstruct and switch between branches itself.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get full session history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.historyResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages": {
            "post": {
                "description": "Sends a JSON user message or multipart form with text and repeated files into a session. Optional reasoning_effort overrides the identity for this turn; disabled_tools removes named tools from this turn only.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Send a message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message to send",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages/{messageID}/edit": {
            "post": {
                "description": "Creates an edited sibling of an assistant message without invoking the LLM, then makes the new message the session's active leaf.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Edit an assistant message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Assistant message ID",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Edited assistant content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.editAssistantMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/messages/{messageID}/fork": {
            "post": {
                "description": "Creates a new session from the source session's conversation path ending at the selected assistant message.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Fork a session from an assistant message",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Assistant message ID",
                        "name": "messageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/regenerate": {
            "post": {
                "description": "Re-answers the nearest ancestor user message on the session's active path, creating a sibling assistant branch rather than a new user message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Regenerate the last reply",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Per-turn generation overrides",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.sendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/workflow-runs": {
            "get": {
                "description": "Lists workflow runs, newest first, with optional workflow-name filter and bounded pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "List workflow runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by workflow name",
                        "name": "workflow",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Result offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowRun"
                            }
                        }
                    }
                }
            }
        },
        "/workflow-runs/{id}": {
            "get": {
                "description": "Returns a workflow run with its ordered steps and transcripts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get a workflow run",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workflow run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.workflowRunDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/workflow-runs/{id}/cancel": {
            "post": {
                "description": "Requests cancellation of an active workflow run.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Cancel a workflow run",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workflow run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/workflow-runs/{id}/stream": {
            "get": {
                "description": "Streams a workflow run's live progress over SSE: run snapshots, step lifecycle, and agent deltas (text/reasoning/tool calls). Ends with a \"done\" event when the run reaches a terminal status.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Stream a workflow run's live progress",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workflow run ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        },
        "/workflows/{name}/runs": {
            "post": {
                "description": "Begins an asynchronous run of the named Workflow in a Project with the given input, returning the created run (202).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Start a workflow run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project and input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.startWorkflowRunRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowRun"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_server.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_registry_Job": {
            "type": "object"
        },
        "datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_registry_Workflow": {
            "type": "object"
        },
        "datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_store_SessionSettings": {
            "type": "object"
        },
        "github_com_Cyvadra_hephaestus_internal_command.SessionTarget": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "project": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_registry.Catalog": {
            "type": "object",
            "properties": {
                "concierges": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "constants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "identities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "impressions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "jobs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "plugin_descriptions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "plugins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tool_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "workflows": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.ChatMessage": {
            "type": "object",
            "properties": {
                "attachments": {
                    "description": "Attachments are files explicitly delivered by the assistant. They are\nloaded for API responses and never included in LLM context messages.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.MessageAttachment"
                    }
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parentMessageID": {
                    "description": "ParentMessageID is nil for the first message of a session.",
                    "type": "integer"
                },
                "reasoningContent": {
                    "description": "ReasoningContent holds chain-of-thought output, when the model\nprovided one.",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sessionID": {
                    "type": "integer"
                },
                "status": {
                    "description": "Status is complete unless generation ended before the Agent finished.",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "toolCallID": {
                    "description": "ToolCallID links a tool-role message back to the assistant\nmessage's tool_calls entry it answers.",
                    "type": "string"
                },
                "toolCalls": {
                    "description": "ToolCalls is the raw tool_calls payload for an assistant message,\nor empty for other roles.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.JobRun": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "job": {
                    "description": "Job is the resolved Job definition at run creation.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_registry_Job"
                        }
                    ]
                },
                "jobName": {
                    "type": "string"
                },
                "localDate": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.JobRunStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.JobRunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "completed_with_errors",
                "failed",
                "cancelled",
                "interrupted"
            ],
            "x-enum-varnames": [
                "JobRunPending",
                "JobRunRunning",
                "JobRunSucceeded",
                "JobRunCompletedWithErrors",
                "JobRunFailed",
                "JobRunCancelled",
                "JobRunInterrupted"
            ]
        },
        "github_com_Cyvadra_hephaestus_internal_store.MessageAttachment": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "messageID": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "projectID": {
                    "type": "integer"
                },
                "sessionID": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.Project": {
            "type": "object",
            "properties": {
                "available_concierge_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.Session": {
            "type": "object",
            "properties": {
                "activeLeafMessageID": {
                    "description": "ActiveLeafMessageID points at the tip of the currently active\nbranch in ChatMessage; nil for a session with no messages yet.",
                    "type": "integer"
                },
                "compressionID": {
                    "description": "CompressionID references the most recently applicable Compression\nrow for this session, if any.",
                    "type": "integer"
                },
                "compressionLastMessageID": {
                    "description": "CompressionLastMessageID is the ChatMessage id up to which\nCompressionID's compression covers.",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "enableWebSearch": {
                    "description": "EnableWebSearch persists whether the web_search/web_fetch tools stay\nenabled for this session. Nil means \"not yet set\" and is treated as\nenabled by clients, keeping legacy sessions backward compatible.",
                    "type": "boolean"
                },
                "flagArchived": {
                    "type": "boolean"
                },
                "flagPinned": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lastMessageTime": {
                    "description": "LastMessageTime is the activity time of the current active message\nbranch. It is independent from UpdatedAt so metadata writes do not\naffect conversation ordering.",
                    "type": "string"
                },
                "project": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Project"
                },
                "projectID": {
                    "type": "integer"
                },
                "reasoningEffort": {
                    "description": "ReasoningEffort is this session's persisted thinking mode\n(none/low/high/max), initialized from the identity at creation and\nupdated whenever the user changes the composer control. Empty is\nbackward compatible with legacy sessions, treated as the identity\ndefault by clients.",
                    "type": "string"
                },
                "settings": {
                    "description": "Settings is the live, mutable configuration for this session.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_store_SessionSettings"
                        }
                    ]
                },
                "sourceConcierge": {
                    "description": "SourceConcierge is the Concierge name used at creation time, kept\nfor reference only; it has no further business influence.",
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "description": "Title and Summary are maintained by the session-summary Plugin\n(title \u003c=20 chars, summary \u003c=300 chars per design doc); both are\nempty until that plugin has run at least once.",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.WorkflowRun": {
            "type": "object",
            "properties": {
                "attempt": {
                    "description": "Attempt is the 1-based retry attempt this run represents.",
                    "type": "integer"
                },
                "bindingIndex": {
                    "type": "integer"
                },
                "concierge": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "input": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "jobName": {
                    "type": "string"
                },
                "jobRunID": {
                    "description": "JobRunID links a scheduler-triggered run; nil for manually started\nruns. JobName and BindingIndex identify the owning binding.",
                    "type": "integer"
                },
                "output": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "projectName": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowRunStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "workflow": {
                    "description": "Workflow is the resolved Workflow definition at run creation.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/datatypes.JSONType-github_com_Cyvadra_hephaestus_internal_registry_Workflow"
                        }
                    ]
                },
                "workflowName": {
                    "type": "string"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.WorkflowRunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed",
                "fatal",
                "cancelled",
                "interrupted"
            ],
            "x-enum-varnames": [
                "WorkflowRunPending",
                "WorkflowRunRunning",
                "WorkflowRunSucceeded",
                "WorkflowRunFailed",
                "WorkflowRunFatal",
                "WorkflowRunCancelled",
                "WorkflowRunInterrupted"
            ]
        },
        "github_com_Cyvadra_hephaestus_internal_store.WorkflowStepRun": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "finishedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "index": {
                    "type": "integer"
                },
                "output": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowStepRunStatus"
                },
                "text": {
                    "type": "string"
                },
                "transcript": {
                    "description": "Transcript is the step's agent-run messages as JSON.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "updatedAt": {
                    "type": "string"
                },
                "workflowRunID": {
                    "type": "integer"
                }
            }
        },
        "github_com_Cyvadra_hephaestus_internal_store.WorkflowStepRunStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "succeeded",
                "failed",
                "fatal",
                "cancelled",
                "interrupted"
            ],
            "x-enum-varnames": [
                "WorkflowRunPending",
                "WorkflowRunRunning",
                "WorkflowRunSucceeded",
                "WorkflowRunFailed",
                "WorkflowRunFatal",
                "WorkflowRunCancelled",
                "WorkflowRunInterrupted"
            ]
        },
        "internal_server.conciergeItem": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "impressions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "plugins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reasoning_effort": {
                    "type": "string"
                },
                "tool_groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_server.createSessionRequest": {
            "type": "object",
            "required": [
                "concierge"
            ],
            "properties": {
                "concierge": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                }
            }
        },
        "internal_server.deleteProjectRequest": {
            "type": "object",
            "properties": {
                "delete_directory": {
                    "type": "boolean"
                }
            }
        },
        "internal_server.editAssistantMessageRequest": {
            "type": "object",
            "required": [
                "active_leaf_message_id",
                "content"
            ],
            "properties": {
                "active_leaf_message_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "reasoning_content": {
                    "type": "string"
                }
            }
        },
        "internal_server.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_server.historyResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.ChatMessage"
                    }
                },
                "reasoning_effort": {
                    "type": "string"
                },
                "session": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.Session"
                }
            }
        },
        "internal_server.jobRunDetail": {
            "type": "object",
            "properties": {
                "run": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.JobRun"
                },
                "workflow_runs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowRun"
                    }
                }
            }
        },
        "internal_server.sendMessageRequest": {
            "type": "object",
            "properties": {
                "active_leaf_message_id": {
                    "description": "ActiveLeafMessageID selects the branch whose context the new turn\ncontinues from. SelectRoot instead starts the turn from an empty path.\nNeither selector changes session state until the turn is persisted.",
                    "type": "integer"
                },
                "disabled_tools": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reasoning_effort": {
                    "type": "string"
                },
                "select_root": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_server.sendMessageResponse": {
            "type": "object",
            "properties": {
                "branch_not_activated": {
                    "description": "BranchNotActivated is set when the turn's output was persisted as a\nreachable but inactive branch because the session's active leaf\nchanged mid-turn.",
                    "type": "boolean"
                },
                "command_response": {
                    "description": "CommandResponse is set (and never persisted) when Text was a slash command.",
                    "type": "string"
                },
                "message": {
                    "description": "Message is the persisted final assistant ChatMessage for a chat turn.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.ChatMessage"
                        }
                    ]
                },
                "metadata": {
                    "description": "Metadata carries any plugin-attached data for this turn (e.g.\nsuggested next-user-message alternatives).",
                    "type": "object",
                    "additionalProperties": {}
                },
                "session_target": {
                    "description": "SessionTarget asks the client to navigate to another existing session.\nIt is set only by slash commands and does not represent a session write.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_command.SessionTarget"
                        }
                    ]
                }
            }
        },
        "internal_server.startWorkflowRunRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "project": {
                    "type": "string"
                }
            }
        },
        "internal_server.updateSessionRequest": {
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "enable_web_search": {
                    "type": "boolean"
                },
                "pinned": {
                    "type": "boolean"
                },
                "reasoning_effort": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_server.workflowRunDetail": {
            "type": "object",
            "properties": {
                "run": {
                    "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowRun"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_Cyvadra_hephaestus_internal_store.WorkflowStepRun"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hephaestus API",
	Description:      "Single-user AI agent framework: sessions, chat turns, slash commands.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
